name: Release

on:
  release:
    types: [published]

jobs:

  build_windows:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Get the version
      id: get_version
      uses: battila7/get-version-action@v2
    
    - name: Build Docker Images 
      run: |
        docker build . --file DockerfileWindows --tag stuartferguson/eventstore_windows:latest --tag stuartferguson/eventstore_windows:${{ steps.get_version.outputs.version }}

    - name: Publish Images to Docker Hub
      run: |
        docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
        docker push stuartferguson/eventstore_windows:latest
        docker push stuartferguson/eventstore_windows:${{ steps.get_version.outputs.version }}
